#!/bin/bash
if [ -z "$@" ]
then
	echo 'No files selected'
	killall gitautopush
else
	true
fi

for staged in "$@"
do
	git add "$staged"
done

git status
echo 'Continue? [y,n]'
read continue

if [ "$continue" = "y" ]
then
	echo 'Commit Message:'
	read message
	git commit -m "'$message'"
	git push
else
	echo 'Canceled'
fi
