#!/bin/python3
import random
import urllib.request

response = urllib.request.urlopen("https://www.mit.edu/~ecprice/wordlist.10000")
words = response.read().decode().splitlines()

word = random.choice(words)
print(word)
